[versions]
agp = "8.13.2"
kotlin = "2.2.21"
navigationSafeArgs = '2.9.6'

coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
lifecycleCommonJvm = "2.10.0"
lifecycleRuntimeKtx = "2.10.0"
recyclerview = '1.4.0'
swiperefreshlayout = '1.2.0'
securityCrypto = '1.1.0'
retrofit = '3.0.0'
converterMoshi = '3.0.0'
moshi = '1.15.2'
moshiKotlin = '1.15.2'
okhttp = '5.3.2'
loggingInterceptor = '5.3.2'
glide = '5.0.5'
svg = '1.4'
gif = '1.2.29'
markdown = '4.6.2'
markdownLinkify = '4.6.2'
markdownStrikethrough = '4.6.2'
markdownTaskList = '4.6.2'
markdownImage = '4.6.2'
appmetrica = '7.14.0'

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgs" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-lifecycle-common-jvm = { group = "androidx.lifecycle", name = "lifecycle-common-jvm", version.ref = "lifecycleCommonJvm" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converterMoshi" }
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
squareup-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
squareup-okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
bumptech-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
caverock-androidsvg = { group = "com.caverock", name = "androidsvg", version.ref = "svg" }
droidsonroids-androidgif = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "gif" }
noties-markdown-core = { group = "io.noties.markwon", name = "core", version.ref = "markdown" }
noties-markdown-linkify = { group = "io.noties.markwon", name = "linkify", version.ref = "markdownLinkify" }
noties-markdown-strikethrough = { group = "io.noties.markwon", name = "ext-strikethrough", version.ref = "markdownStrikethrough" }
noties-markdown-tasklist = { group = "io.noties.markwon", name = "ext-tasklist", version.ref = "markdownTaskList" }
noties-markdown-image = { group = "io.noties.markwon", name = "image", version.ref = "markdownImage" }
appmetrica = { group = "io.appmetrica.analytics", name = "analytics", version.ref = "appmetrica" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
